version: '3.8'

services:
  frontend:
    container_name: frontend
    build: frontend
    ports:
      - 5000:5000
  backend:
    container_name: backend
    build: backend
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=sergtsop
      - DB_NAME=database
      - DB_HOST=postgres
  redis:
    container_name: redis
    image: redis
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sergtsop
      - POSTGRES_DB=database
