version: '3.8'

services:
  frontend:
    container_name: frontend
    build: frontend
    environment: 
      - API_URL=http://localhost/api
  backend:
    container_name: backend
    build: backend
    volumes: 
      - ./logs.txt:/backend-example-docker/logs.txt
    environment:
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=sergtsop
      - DB_NAME=database
      - DB_HOST=postgres
      - FRONT_URL=http://localhost
  redis:
    container_name: redis
    image: redis
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sergtsop
      - POSTGRES_DB=database
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
